-- Epic 18.1: Pitch drafts schema for AI-assisted pitch content generation
-- Dependencies: profiles table, handle_updated_at() function

-- ============================================================================
-- PITCH DRAFTS TABLE
-- ============================================================================

create table if not exists public.pitch_drafts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  template_type text check (template_type in (
    'mid_size',
    'regional',
    'wofex_booth'
  )), -- null for custom pitches
  status text not null default 'draft' check (status in (
    'draft',
    'ready',
    'exported'
  )),
  exported_at timestamptz,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- Prevent empty titles
alter table public.pitch_drafts
add constraint pitch_drafts_title_not_empty check (trim(title) <> '');

-- Add comments for documentation
comment on table public.pitch_drafts is 'Container for distributor pitch presentations. Stores overall pitch metadata and status.';
comment on column public.pitch_drafts.title is 'User-defined title for the pitch draft';
comment on column public.pitch_drafts.template_type is 'Template type: mid_size, regional, wofex_booth, or null for custom';
comment on column public.pitch_drafts.status is 'Workflow status: draft, ready, exported';
comment on column public.pitch_drafts.exported_at is 'When the pitch was exported to PDF (null if not exported)';

-- ============================================================================
-- PITCH SECTIONS TABLE (AI-generated content)
-- ============================================================================

create table if not exists public.pitch_sections (
  id uuid primary key default gen_random_uuid(),
  pitch_draft_id uuid not null references public.pitch_drafts(id) on delete cascade,
  section_type text not null check (section_type in (
    'market_opportunity',
    'competitive_positioning',
    'trend_alignment'
  )),
  content text not null,
  ai_generated boolean default true not null,
  user_edited boolean default false not null,
  confidence_score numeric(3,2) check (confidence_score >= 0 and confidence_score <= 1),
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- Prevent empty content
alter table public.pitch_sections
add constraint pitch_sections_content_not_empty check (trim(content) <> '');

-- Add comments for documentation
comment on table public.pitch_sections is 'Individual AI-generated or user-edited sections within a pitch draft.';
comment on column public.pitch_sections.pitch_draft_id is 'Foreign key to parent pitch draft';
comment on column public.pitch_sections.section_type is 'Type of section: market_opportunity, competitive_positioning, trend_alignment';
comment on column public.pitch_sections.content is 'The actual pitch content text';
comment on column public.pitch_sections.ai_generated is 'Whether this section was generated by AI';
comment on column public.pitch_sections.user_edited is 'Whether user has modified the AI-generated content';
comment on column public.pitch_sections.confidence_score is 'AI confidence score 0.00-1.00 based on MI data quality';

-- ============================================================================
-- PITCH SECTION SOURCES TABLE (junction for MI source tracking)
-- ============================================================================

create table if not exists public.pitch_section_sources (
  id uuid primary key default gen_random_uuid(),
  section_id uuid not null references public.pitch_sections(id) on delete cascade,
  source_type text not null check (source_type in (
    'companies',
    'products',
    'consumers',
    'trends',
    'research_docs'
  )),
  source_id uuid not null,
  relevance_score numeric(3,2) check (relevance_score >= 0 and relevance_score <= 1),
  created_at timestamptz default now() not null
);

-- Add comments for documentation
comment on table public.pitch_section_sources is 'Junction table tracking which MI entities were used to generate each section.';
comment on column public.pitch_section_sources.section_id is 'Foreign key to pitch section';
comment on column public.pitch_section_sources.source_type is 'Type of MI source: companies, products, consumers, trends, research_docs';
comment on column public.pitch_section_sources.source_id is 'UUID of the source entity in its respective table';
comment on column public.pitch_section_sources.relevance_score is 'How relevant this source was for the generated content';

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Pitch drafts indexes
create index pitch_drafts_status_idx on public.pitch_drafts (status);
create index pitch_drafts_template_type_idx on public.pitch_drafts (template_type);
create index pitch_drafts_created_at_idx on public.pitch_drafts (created_at desc);

-- Pitch sections indexes
create index idx_pitch_sections_draft on public.pitch_sections (pitch_draft_id);
create index pitch_sections_section_type_idx on public.pitch_sections (section_type);
create index pitch_sections_ai_generated_idx on public.pitch_sections (ai_generated);

-- Pitch section sources indexes
create index idx_pitch_section_sources_section on public.pitch_section_sources (section_id);
create index pitch_section_sources_type_idx on public.pitch_section_sources (source_type);

-- ============================================================================
-- AUTO-UPDATE TIMESTAMP TRIGGERS
-- ============================================================================

-- Reuse existing handle_updated_at function from profiles migration
drop trigger if exists on_pitch_drafts_updated on public.pitch_drafts;
create trigger on_pitch_drafts_updated
  before update on public.pitch_drafts
  for each row execute procedure public.handle_updated_at();

drop trigger if exists on_pitch_sections_updated on public.pitch_sections;
create trigger on_pitch_sections_updated
  before update on public.pitch_sections
  for each row execute procedure public.handle_updated_at();

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================

alter table public.pitch_drafts enable row level security;
alter table public.pitch_sections enable row level security;
alter table public.pitch_section_sources enable row level security;

-- Pitch Drafts RLS Policies
create policy "Authorized users can view pitch drafts"
  on public.pitch_drafts for select
  to authenticated
  using (
    (select auth.email()) in (
      select email from public.profiles where role in ('maho', 'kel')
    )
  );

create policy "Authorized users can create pitch drafts"
  on public.pitch_drafts for insert
  to authenticated
  with check (
    (select auth.email()) in (
      select email from public.profiles where role in ('maho', 'kel')
    )
  );

create policy "Authorized users can update pitch drafts"
  on public.pitch_drafts for update
  to authenticated
  using (
    (select auth.email()) in (
      select email from public.profiles where role in ('maho', 'kel')
    )
  )
  with check (
    (select auth.email()) in (
      select email from public.profiles where role in ('maho', 'kel')
    )
  );

create policy "Authorized users can delete pitch drafts"
  on public.pitch_drafts for delete
  to authenticated
  using (
    (select auth.email()) in (
      select email from public.profiles where role in ('maho', 'kel')
    )
  );

-- Pitch Sections RLS Policies
create policy "Authorized users can view pitch sections"
  on public.pitch_sections for select
  to authenticated
  using (
    (select auth.email()) in (
      select email from public.profiles where role in ('maho', 'kel')
    )
  );

create policy "Authorized users can create pitch sections"
  on public.pitch_sections for insert
  to authenticated
  with check (
    (select auth.email()) in (
      select email from public.profiles where role in ('maho', 'kel')
    )
  );

create policy "Authorized users can update pitch sections"
  on public.pitch_sections for update
  to authenticated
  using (
    (select auth.email()) in (
      select email from public.profiles where role in ('maho', 'kel')
    )
  )
  with check (
    (select auth.email()) in (
      select email from public.profiles where role in ('maho', 'kel')
    )
  );

create policy "Authorized users can delete pitch sections"
  on public.pitch_sections for delete
  to authenticated
  using (
    (select auth.email()) in (
      select email from public.profiles where role in ('maho', 'kel')
    )
  );

-- Pitch Section Sources RLS Policies
create policy "Authorized users can view pitch section sources"
  on public.pitch_section_sources for select
  to authenticated
  using (
    (select auth.email()) in (
      select email from public.profiles where role in ('maho', 'kel')
    )
  );

create policy "Authorized users can create pitch section sources"
  on public.pitch_section_sources for insert
  to authenticated
  with check (
    (select auth.email()) in (
      select email from public.profiles where role in ('maho', 'kel')
    )
  );

create policy "Authorized users can delete pitch section sources"
  on public.pitch_section_sources for delete
  to authenticated
  using (
    (select auth.email()) in (
      select email from public.profiles where role in ('maho', 'kel')
    )
  );
